interface City{
    ciudad: String
}

export const CITIES:City[] = [
        {ciudad:	'APARTADÓ'},
        {ciudad:	'ARMENIA'},
        {ciudad:	'BARRANCABERMEJA'},
        {ciudad:	'BARRANQUILLA'},
        {ciudad:	'BELLO'},
        {ciudad:	'BOGOTÁ'},
        {ciudad:	'BUCARAMANGA'},
        {ciudad:	'BUENAVENTURA'},
        {ciudad:	'CALÍ'},
        {ciudad:	'CARTAGENA'},
        {ciudad:	'CARTAGO'},
        {ciudad:	'CAUCASIA'},
        {ciudad:	'CHÍA'},
        {ciudad:	'CIÉNAGA'},
        {ciudad:	'CÚCUTA'},
        {ciudad:	'DOSQUEBRADAS'},
        {ciudad:	'DUITAMA'},
        {ciudad:	'ENVIGADO'},
        {ciudad:	'FACATATIVÁ'},
        {ciudad:	'FLORENCIA'},
        {ciudad:	'FLORIDABLANCA'},
        {ciudad:	'FUSAGASUGÁ'},
        {ciudad:	'GIRARDOT'},
        {ciudad:	'GIRÓN'},
        {ciudad:	'GUADALAJARA DE BUGA'},
        {ciudad:	'IBAGUÉ'},
        {ciudad:	'IPIALES'},
        {ciudad:	'ITAGUI'},
        {ciudad:	'JAMUNDI'},
        {ciudad:	'LORICA'},
        {ciudad:	'MAGANGUÉ'},
        {ciudad:	'MAICAO'},
        {ciudad:	'MALAMBO'},
        {ciudad:	'MANIZALES'},
        {ciudad:	'MEDELLÍN'},
        {ciudad:	'MONTERÍA'},
        {ciudad:	'NEIVA'},
        {ciudad:	'OCAÑA'},
        {ciudad:	'PALMIRA'},
        {ciudad:	'PASTO'},
        {ciudad:	'PEREIRA'},
        {ciudad:	'PIEDECUESTA'},
        {ciudad:	'PITALITO'},
        {ciudad:	'POPAYÁN'},
        {ciudad:	'QUIBDÓ'},
        {ciudad:	'RIOHACHA'},
        {ciudad:	'RIONEGRO'},
        {ciudad:	'SAN ANDRÉS DE TUMACO'},
        {ciudad:	'SANTA MARTA'},
        {ciudad:	'SINCELEJO'},
        {ciudad:	'SOACHA'},
        {ciudad:	'SOGAMOSO'},
        {ciudad:	'SOLEDAD'},
        {ciudad:	'TULUÁ'},
        {ciudad:	'TUNJA'},
        {ciudad:	'TURBO'},
        {ciudad:	'URIBIA'},
        {ciudad:	'VALLEDUPAR'},
        {ciudad:	'VILLAVICENCIO'},
        {ciudad:	'YOPAL'},
        {ciudad:	'YUMBO'},
        {ciudad:	'ZIPAQUIRÁ'},
        
]